### ISSUE TITLE
Cassandra driver fails to connect to Simulacron using Java API

### ISSUE THREAD

**Issue by kobik** [datastax/simulacron#120]
Hi,

I'm trying to make cassandra driver to connect to simulacron using Java  API without any success and appreciate any help with trying to find out the problem.

Not sure what am I missing.

I tried creating a DC
```scala
    val sCluster = ClusterSpec
      .builder()
      .build()

    sCluster
      .addDataCenter()
      .build()
      .addNode()
      .withCassandraVersion("3.0.10")
      .build()
    
    val server = Server.builder().build()
    val cluster = server.register(sCluster)
```

but when the driver tries to connect it fails with the following logs
```log
16:37:34.411 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] Connection established, initializing transport
16:37:34.417 [simulacron-io-worker-2-2] DEBUG com.datastax.oss.simulacron.server.Server - Got new connection [id: 0x3ba10f07, L:/127.0.0.1:9042 - R:/127.0.0.1:57933]
16:37:34.427 [cluster1-nio-worker-0] TRACE com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false], stream 0, writing request STARTUP {CQL_VERSION=3.0.0}
16:37:34.419 [simulacron-io-worker-2-2] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x3ba10f07, L:/127.0.0.1:9042 - R:/127.0.0.1:57933]
java.lang.NoClassDefFoundError: io/netty/handler/flush/FlushConsolidationHandler
	at com.datastax.oss.simulacron.server.Server$Initializer.initChannel(Server.java:865) ~[simulacron-native-server-0.11.0.jar:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:136) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:122) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:115) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1253) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:136) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:122) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:784) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:445) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:368) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [netty-common-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:394) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [netty-common-4.0.37.Final.jar:4.0.37.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: io.netty.handler.flush.FlushConsolidationHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
	... 17 more
16:37:34.448 [cluster1-nio-worker-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
16:37:34.448 [cluster1-nio-worker-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
16:37:34.467 [cluster1-nio-worker-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
16:37:34.479 [cluster1-nio-worker-0] TRACE com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false], stream 0, request sent successfully
16:37:34.481 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] connection error
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_192]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_192]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_192]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_192]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_192]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-buffer-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:897) ~[netty-buffer-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.37.Final.jar:4.0.37.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
16:37:34.482 [cluster1-nio-worker-0] TRACE com.datastax.driver.core.Host.STATES - Defuncting Connection[/127.0.0.1:9042-1, inFlight=0, closed=false]
com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Unexpected exception triggered (java.io.IOException: Connection reset by peer)
	at com.datastax.driver.core.Connection$Dispatcher.exceptionCaught(Connection.java:1049) [cassandra-driver-core-3.1.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1241) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:878) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:87) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:162) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) [netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.37.Final.jar:4.0.37.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_192]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_192]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_192]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_192]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_192]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-buffer-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:897) ~[netty-buffer-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	... 6 more
16:37:34.484 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] preventing new connections for the next 1000 ms
16:37:34.484 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] failed, remaining = 0
16:37:34.485 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=true] closing connection
16:37:34.485 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Not terminating Connection[/127.0.0.1:9042-1, inFlight=0, closed=true]: there are still pending requests
16:37:34.487 [ScalaTest-run] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /127.0.0.1:9042 connection, no more host to try
com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Connection has been closed
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1131) ~[cassandra-driver-core-3.1.0.jar:?]
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1116) ~[cassandra-driver-core-3.1.0.jar:?]
	at com.datastax.driver.core.Connection.defunct(Connection.java:424) ~[cassandra-driver-core-3.1.0.jar:?]
	at com.datastax.driver.core.Connection$Dispatcher.exceptionCaught(Connection.java:1049) ~[cassandra-driver-core-3.1.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:244) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1241) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:273) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:252) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:878) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:87) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:162) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.37.Final.jar:4.0.37.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_192]
```

why I'm trying to open connection using Simulacron CLI it seems like it successfully connected
```bash
java -jar simulacron-standalone-0.10.0.jar -s 9042 --httpintf 0.0.0.0 -v
```
```log
16:45:42.752 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] Connection established, initializing transport
16:45:42.780 [cluster1-nio-worker-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
16:45:42.781 [cluster1-nio-worker-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
16:45:42.800 [cluster1-nio-worker-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
16:45:42.819 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
16:45:42.822 [ScalaTest-run] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] Refreshing node list and token map
16:45:42.893 [ScalaTest-run] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] Refreshing schema
16:45:43.023 [ScalaTest-run] DEBUG com.datastax.driver.core.ReplicationStrategy$NetworkTopologyStrategy - Computing token to replica map for keyspace: sandbox_review_koa_typescript_cassandra_graceful.
16:45:43.027 [ScalaTest-run] DEBUG com.datastax.driver.core.ReplicationStrategy$NetworkTopologyStrategy - Token to replica map computation for keyspace sandbox_review_koa_typescript_cassandra_graceful completed in 4 milliseconds
16:45:43.047 [ScalaTest-run] DEBUG com.datastax.driver.core.Host.STATES - [Control connection] established to /127.0.0.1:9042
16:45:43.047 [ScalaTest-run] INFO  com.datastax.driver.core.policies.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
16:45:43.049 [ScalaTest-run] INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
```

Can you please advise?
What am I missing?

Thanks

**Comment by kobik** [comment]
Found out that there was a mismatch in datacenter name.

Thanks
